apiVersion: demo.gaurangkudale.github.io/v1alpha1
kind: Myoperator
metadata:
  labels:
    app.kubernetes.io/name: first-operator
    app.kubernetes.io/managed-by: kustomize
  name: myoperator-sample
spec:
  # TODO(user): Add fields here
